
ALTER TABLE users ALTER COLUMN user_id SET DATA TYPE BIGINT;
ALTER TABLE snippets ALTER COLUMN snippet_id SET DATA TYPE BIGINT;
ALTER TABLE snippets ALTER COLUMN user_id SET DATA TYPE BIGINT;
ALTER TABLE snippets ALTER COLUMN language_id SET DATA TYPE BIGINT;
ALTER TABLE versions ALTER COLUMN version_id SET DATA TYPE BIGINT;
ALTER TABLE versions ALTER COLUMN snippet_id SET DATA TYPE BIGINT;
ALTER TABLE versions ALTER COLUMN version SET DATA TYPE BIGINT;
ALTER TABLE languages ALTER COLUMN language_id SET DATA TYPE BIGINT;
ALTER TABLE ratings ALTER COLUMN rating_id SET DATA TYPE BIGINT;
ALTER TABLE ratings ALTER COLUMN snippet_id SET DATA TYPE BIGINT;
ALTER TABLE ratings ALTER COLUMN user_id SET DATA TYPE BIGINT;
ALTER TABLE comments ALTER COLUMN comment_id SET DATA TYPE BIGINT;
ALTER TABLE comments ALTER COLUMN snippet_id SET DATA TYPE BIGINT;
ALTER TABLE comments ALTER COLUMN user_id SET DATA TYPE BIGINT;
ALTER TABLE tags ALTER COLUMN tag_id SET DATA TYPE BIGINT;
ALTER TABLE snippettags ALTER COLUMN snippet_id SET DATA TYPE BIGINT;
ALTER TABLE snippettags ALTER COLUMN tag_id SET DATA TYPE BIGINT;
