
DROP VIEW IF EXISTS view_snippets CASCADE;
DROP VIEW IF EXISTS view_snippet_by_id CASCADE;
DROP VIEW IF EXISTS view_snippet_versions_by_id CASCADE;
DROP VIEW IF EXISTS view_version_by_id CASCADE;
DROP VIEW IF EXISTS view_comments_by_snippet CASCADE;

DROP PROCEDURE IF EXISTS create_snippet;
DROP PROCEDURE IF EXISTS add_version;
DROP PROCEDURE IF EXISTS rate_snippet;
DROP PROCEDURE IF EXISTS add_comment;
DROP PROCEDURE IF EXISTS add_snippet_tag;
DROP PROCEDURE IF EXISTS soft_delete_snippet;


ALTER TABLE users ALTER COLUMN user_id SET DATA TYPE BIGINT;
ALTER TABLE snippets ALTER COLUMN snippet_id SET DATA TYPE BIGINT;
ALTER TABLE snippets ALTER COLUMN user_id SET DATA TYPE BIGINT;
ALTER TABLE snippets ALTER COLUMN language_id SET DATA TYPE BIGINT;
ALTER TABLE versions ALTER COLUMN version_id SET DATA TYPE BIGINT;
ALTER TABLE versions ALTER COLUMN snippet_id SET DATA TYPE BIGINT;
ALTER TABLE versions ALTER COLUMN version SET DATA TYPE BIGINT;
ALTER TABLE languages ALTER COLUMN language_id SET DATA TYPE BIGINT;
ALTER TABLE ratings ALTER COLUMN rating_id SET DATA TYPE BIGINT;
ALTER TABLE ratings ALTER COLUMN snippet_id SET DATA TYPE BIGINT;
ALTER TABLE ratings ALTER COLUMN user_id SET DATA TYPE BIGINT;
ALTER TABLE comments ALTER COLUMN comment_id SET DATA TYPE BIGINT;
ALTER TABLE comments ALTER COLUMN snippet_id SET DATA TYPE BIGINT;
ALTER TABLE comments ALTER COLUMN user_id SET DATA TYPE BIGINT;
ALTER TABLE tags ALTER COLUMN tag_id SET DATA TYPE BIGINT;
ALTER TABLE snippettags ALTER COLUMN snippet_id SET DATA TYPE BIGINT;
ALTER TABLE snippettags ALTER COLUMN tag_id SET DATA TYPE BIGINT;
