CREATE TABLE "users" (
  "userId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userGuid" GUID NOT NULL,
  "createdAt" DATETIME2 NOT NULL
);

CREATE TABLE "languages" (
  "languageId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "languageName" VARCHAR(256) NOT NULL
);

CREATE TABLE "snippets" (
  "snippetId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INT NOT NULL,
  "title" VARCHAR(256) NOT NULL,
  "description" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "languageId" INT NOT NULL,
  "updatedAt" DATETIME2 NOT NULL,
  "isDeleted" BIT  NOT NULL DEFAULT 0,
  "createdAt" DATETIME2 NOT NULL
);

CREATE TABLE "versions" (
  "versionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "snippetId" INT NOT NULL,
  "version" VARCHAR(100) NOT NULL,
  "code" TEXT NOT NULL,
  "createdAt" DATETIME2 NOT NULL
);

CREATE TABLE "tags" (
  "tagId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tagName" VARCHAR(256) NOT NULL
);

CREATE TABLE "snippettags" (
  "snippetId" INT NOT NULL,
  "tagId" INT NOT NULL
);

CREATE TABLE "ratings" (
  "ratingId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "snippetId" INT NOT NULL,
  "userId" INT NOT NULL,
  "rating" INT NOT NULL,
  "createdAt" DATETIME2 NOT NULL
);

CREATE TABLE "comments" (
  "commentId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "snippetId" INT NOT NULL,
  "userId" INT NOT NULL,
  "comment" VARCHAR(256) NOT NULL,
  "createdAt" DATETIME2 NOT NULL
);

ALTER TABLE "snippets" ADD FOREIGN KEY ("userId") REFERENCES "users" ("userId");

ALTER TABLE "snippets" ADD FOREIGN KEY ("languageId") REFERENCES "languages" ("languageId");

ALTER TABLE "versions" ADD FOREIGN KEY ("snippetId") REFERENCES "snippets" ("snippetId");

ALTER TABLE "snippettags" ADD FOREIGN KEY ("snippetId") REFERENCES "snippets" ("snippetId");

ALTER TABLE "snippettags" ADD FOREIGN KEY ("tagId") REFERENCES "tags" ("tagId");

ALTER TABLE "ratings" ADD FOREIGN KEY ("snippetId") REFERENCES "snippets" ("snippetId");

ALTER TABLE "ratings" ADD FOREIGN KEY ("userId") REFERENCES "users" ("userId");

ALTER TABLE "comments" ADD FOREIGN KEY ("snippetId") REFERENCES "snippets" ("snippetId");

ALTER TABLE "comments" ADD FOREIGN KEY ("userId") REFERENCES "users" ("userId");