name: Terraform and Spring Boot Application Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: 'Build Spring Boot Application'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: application
        path: target/*.jar

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    needs: build
    
    # Use the Bash shell regardless of runner platform
    defaults:
      run:
        shell: bash
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1
    
    - name: Terraform Init
      run: |
        cd terraform/environments/dev
        terraform init
      
    - name: Terraform Format
      run: |
        cd terraform/environments/dev
        terraform fmt -check -recursive
      
    - name: Terraform Plan
      id: plan
      run: |
        cd terraform/environments/dev
        terraform plan -var-file=terraform.tfvars -no-color
      continue-on-error: true
    
    - name: Update Pull Request
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          <details><summary>Show Plan</summary>
          
          \`\`\`terraform
          ${process.env.PLAN}
          \`\`\`
          
          </details>`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
    
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        cd terraform/environments/dev
        terraform apply -var-file=terraform.tfvars -auto-approve
  
  database-migrations:
    name: 'Database Migrations'
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1
    
    - name: Setup Flyway
      run: |
        wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.8.1/flyway-commandline-9.8.1-linux-x64.tar.gz | tar -xvz
        sudo ln -s $(pwd)/flyway-9.8.1/flyway /usr/local/bin/flyway
    
    - name: Terraform Init
      run: |
        cd terraform/environments/dev
        terraform init
    
    - name: Run Database Migrations
      run: |
        cd terraform/environments/dev
        export DB_ENDPOINT=$(terraform output -raw db_endpoint)
        export DB_NAME=$(terraform output -raw db_name)
        export DB_HOST=$(echo "${DB_ENDPOINT}" | cut -d':' -f1)
        export DB_PORT=$(echo "${DB_ENDPOINT}" | cut -d':' -f2)
        
        # Create temporary Flyway configuration
        TEMP_CONF=$(mktemp)
        cat ../../flyway/conf/flyway.conf > "${TEMP_CONF}"
        cat ../../flyway/conf/flyway-dev.conf >> "${TEMP_CONF}"
        echo "flyway.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}" >> "${TEMP_CONF}"
        echo "flyway.user=${{ secrets.DB_USERNAME }}" >> "${TEMP_CONF}"
        echo "flyway.password=${{ secrets.DB_PASSWORD }}" >> "${TEMP_CONF}"
        
        # Run Flyway migrations
        flyway -configFiles="${TEMP_CONF}" migrate

  deploy:
    name: 'Deploy to Elastic Beanstalk'
    runs-on: ubuntu-latest
    needs: [build, database-migrations]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
    
    - name: Download application artifact
      uses: actions/download-artifact@v3
      with:
        name: application
        path: ./application
    
    - name: Terraform Init
      run: |
        cd terraform/environments/dev
        terraform init
    
    - name: Get Elastic Beanstalk Info
      run: |
        cd terraform/environments/dev
        echo "EB_APP_NAME=$(terraform output -raw eb_application_name)" >> $GITHUB_ENV
        echo "EB_ENV_NAME=$(terraform output -raw eb_environment_name)" >> $GITHUB_ENV
    
    - name: Create application version bundle
      run: |
        # Find the JAR file
        JAR_FILE=$(find ./application -name "*.jar" | head -n 1)
        
        # Create an application version zip file for Elastic Beanstalk
        mkdir -p .ebextensions
        
        # Create Procfile for EB to run the Spring Boot jar
        echo "web: java -jar $JAR_FILE --server.port=5000" > Procfile
        
        # Create .ebextensions config file to set Java options
        cat > .ebextensions/01_jvmoptions.config <<EOL
        option_settings:
          aws:elasticbeanstalk:application:environment:
            JAVA_TOOL_OPTIONS: "-XX:+UseG1GC -Xms256m -Xmx512m"
        EOL
        
        # Create zip bundle for deployment
        zip -r application.zip Procfile .ebextensions $JAR_FILE
    
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.EB_APP_NAME }}
        environment_name: ${{ env.EB_ENV_NAME }}
        version_label: ${{ github.sha }}
        region: af-south-1
        deployment_package: application.zip
        wait_for_environment_recovery: 300